/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khoaluantotnghiep.view;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        UIManager.put("PopupMenu.border", BorderFactory.createEmptyBorder());
        initComponents();
    }

    public JButton getBtnAddNewUser() {
        return btnAddNewUser;
    }

    public JDialog getDialogPackSoftware() {
        return dialogPackSoftware;
    }

    public JTextField getDlAddress() {
        return dlAddress;
    }

    public JButton getDlBtnSave() {
        return dlBtnSave;
    }

    public JTextField getDlEmail() {
        return dlEmail;
    }

    public JTextField getDlFullName() {
        return dlFullName;
    }

    public JTextArea getDlNote() {
        return dlNote;
    }

    public JTextField getDlOrganization() {
        return dlOrganization;
    }

    public JTextField getDlSerial() {
        return dlSerial;
    }

    public JLabel getDlSerialPackLogs() {
        return dlSerialPackLogs;
    }

    public JTextArea getLogsPack() {
        return logsPack;
    }

    public JMenuItem getMenuItemEditUser() {
        return menuItemEditUser;
    }

    public JMenuItem getMenuItemPackSoftWare() {
        return menuItemPackSoftWare;
    }

    public JMenuItem getMenuItemRemoveUser() {
        return menuItemRemoveUser;
    }

    public JPopupMenu getPopupTableUser() {
        return popupTableUser;
    }

    public JTable getTableUsers() {
        return tableUsers;
    }

    public JTextField getTxtLookupUser() {
        return txtLookupUser;
    }

    public JDialog getDialogAddNewUser() {
        return dialogAddNewUser;
    }

    public JDialog getDialogEditUser() {
        return dialogEditUser;
    }

    public JButton getDlAddNewUser_Add() {
        return dlAddNewUser_Add;
    }

    public JTextField getDlAddNewUser_Address() {
        return dlAddNewUser_Address;
    }

    public JTextField getDlAddNewUser_FullName() {
        return dlAddNewUser_FullName;
    }

    public JTextArea getDlAddNewUser_Note() {
        return dlAddNewUser_Note;
    }

    public JTextField getDlAddNewUser_Organization() {
        return dlAddNewUser_Organization;
    }

    public JTextField getDlAddNewUser_Email() {
        return dlAddNewUser_Email;
    }

    public JButton getBtnCreatePass() {
        return btnCreatePass;
    }

    public JButton getBtnHash() {
        return btnHash;
    }

    public JDialog getDialogCreatePassword() {
        return dialogCreatePassword;
    }

    public JTextArea getTxtBcrypt() {
        return txtBcrypt;
    }

    public JTextField getTxtPlainTextPass() {
        return txtPlainTextPass;
    }

    public JButton getDlBtnBuild() {
        return dlBtnBuild;
    }

    public JTextField getDlPackTxtPassword() {
        return dlPackTxtPassword;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupTableUser = new javax.swing.JPopupMenu();
        menuItemEditUser = new javax.swing.JMenuItem();
        menuItemRemoveUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemPackSoftWare = new javax.swing.JMenuItem();
        dialogEditUser = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dlSerial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dlFullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dlOrganization = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dlAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dlEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dlNote = new javax.swing.JTextArea();
        dlBtnSave = new javax.swing.JButton();
        dialogPackSoftware = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dlSerialPackLogs = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logsPack = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        dlPackTxtPassword = new javax.swing.JTextField();
        dlBtnBuild = new javax.swing.JButton();
        dialogAddNewUser = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dlAddNewUser_FullName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dlAddNewUser_Organization = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dlAddNewUser_Address = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dlAddNewUser_Email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dlAddNewUser_Note = new javax.swing.JTextArea();
        dlAddNewUser_Add = new javax.swing.JButton();
        dialogCreatePassword = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPlainTextPass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBcrypt = new javax.swing.JTextArea();
        btnHash = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLookupUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        btnCreatePass = new javax.swing.JButton();

        menuItemEditUser.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        menuItemEditUser.setText("Edit User");
        popupTableUser.add(menuItemEditUser);

        menuItemRemoveUser.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        menuItemRemoveUser.setText("Remove User");
        popupTableUser.add(menuItemRemoveUser);
        popupTableUser.add(jSeparator1);

        menuItemPackSoftWare.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        menuItemPackSoftWare.setText("Build Software");
        popupTableUser.add(menuItemPackSoftWare);

        dialogEditUser.setTitle("Edit User");
        dialogEditUser.setMinimumSize(new java.awt.Dimension(550, 550));
        dialogEditUser.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogEditUser.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(550, 550));
        jPanel2.setMinimumSize(new java.awt.Dimension(550, 550));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Serial");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        dlSerial.setEditable(false);
        dlSerial.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel2.add(dlSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 410, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Full name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        dlFullName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel2.add(dlFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 410, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Organization");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 30));

        dlOrganization.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel2.add(dlOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 410, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 30));

        dlAddress.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel2.add(dlAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 410, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Note");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 140));

        dlEmail.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel2.add(dlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 410, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 30));

        dlNote.setColumns(20);
        dlNote.setRows(5);
        jScrollPane2.setViewportView(dlNote);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 410, 140));

        dlBtnSave.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        dlBtnSave.setText("Save");
        jPanel2.add(dlBtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 210, 60));

        javax.swing.GroupLayout dialogEditUserLayout = new javax.swing.GroupLayout(dialogEditUser.getContentPane());
        dialogEditUser.getContentPane().setLayout(dialogEditUserLayout);
        dialogEditUserLayout.setHorizontalGroup(
            dialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(dialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogEditUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogEditUserLayout.setVerticalGroup(
            dialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(dialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogEditUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogPackSoftware.setTitle("Build Software");
        dialogPackSoftware.setMinimumSize(new java.awt.Dimension(700, 600));
        dialogPackSoftware.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogPackSoftware.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogPackSoftware.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setText("Password");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        dlSerialPackLogs.setText("serial");
        jPanel3.add(dlSerialPackLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 11, 300, 20));

        logsPack.setBackground(new java.awt.Color(0, 0, 0));
        logsPack.setColumns(20);
        logsPack.setForeground(new java.awt.Color(0, 204, 0));
        logsPack.setRows(5);
        jScrollPane3.setViewportView(logsPack);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 480));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel14.setText("Serial");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, -1, 23));

        dlPackTxtPassword.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jPanel3.add(dlPackTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 280, 30));

        dlBtnBuild.setFont(new java.awt.Font("SansSerif", 3, 13)); // NOI18N
        dlBtnBuild.setText("Build Digital Signature Software");
        jPanel3.add(dlBtnBuild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, 30));

        javax.swing.GroupLayout dialogPackSoftwareLayout = new javax.swing.GroupLayout(dialogPackSoftware.getContentPane());
        dialogPackSoftware.getContentPane().setLayout(dialogPackSoftwareLayout);
        dialogPackSoftwareLayout.setHorizontalGroup(
            dialogPackSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(dialogPackSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogPackSoftwareLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogPackSoftwareLayout.setVerticalGroup(
            dialogPackSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(dialogPackSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogPackSoftwareLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogAddNewUser.setTitle("Edit User");
        dialogAddNewUser.setMinimumSize(new java.awt.Dimension(550, 500));
        dialogAddNewUser.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogAddNewUser.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(550, 500));
        jPanel4.setMinimumSize(new java.awt.Dimension(550, 500));
        jPanel4.setPreferredSize(new java.awt.Dimension(550, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Full name");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        dlAddNewUser_FullName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel4.add(dlAddNewUser_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 410, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Organization");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        dlAddNewUser_Organization.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel4.add(dlAddNewUser_Organization, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 410, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Address");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        dlAddNewUser_Address.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel4.add(dlAddNewUser_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 410, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Note");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 30));

        dlAddNewUser_Email.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel4.add(dlAddNewUser_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 410, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Email");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 30));

        dlAddNewUser_Note.setColumns(20);
        dlAddNewUser_Note.setRows(5);
        jScrollPane4.setViewportView(dlAddNewUser_Note);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 410, 140));

        dlAddNewUser_Add.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        dlAddNewUser_Add.setText("Add");
        jPanel4.add(dlAddNewUser_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 130, 30));

        javax.swing.GroupLayout dialogAddNewUserLayout = new javax.swing.GroupLayout(dialogAddNewUser.getContentPane());
        dialogAddNewUser.getContentPane().setLayout(dialogAddNewUserLayout);
        dialogAddNewUserLayout.setHorizontalGroup(
            dialogAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(dialogAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAddNewUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogAddNewUserLayout.setVerticalGroup(
            dialogAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(dialogAddNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogAddNewUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        dialogCreatePassword.setTitle("Create Password");
        dialogCreatePassword.setMinimumSize(new java.awt.Dimension(600, 350));
        dialogCreatePassword.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogCreatePassword.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel5.setMaximumSize(new java.awt.Dimension(600, 350));
        jPanel5.setMinimumSize(new java.awt.Dimension(600, 350));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 350));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setText("Bcrypt Hash Password");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtPlainTextPass.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel5.add(txtPlainTextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 550, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel10.setText("PlainText Password");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        txtBcrypt.setColumns(20);
        txtBcrypt.setRows(5);
        jScrollPane5.setViewportView(txtBcrypt);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, -1));

        btnHash.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHash.setText("Hash");
        jPanel5.add(btnHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 240, 200, 30));

        javax.swing.GroupLayout dialogCreatePasswordLayout = new javax.swing.GroupLayout(dialogCreatePassword.getContentPane());
        dialogCreatePassword.getContentPane().setLayout(dialogCreatePasswordLayout);
        dialogCreatePasswordLayout.setHorizontalGroup(
            dialogCreatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(dialogCreatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogCreatePasswordLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogCreatePasswordLayout.setVerticalGroup(
            dialogCreatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(dialogCreatePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogCreatePasswordLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Signature Software - Administrator");
        setMaximumSize(new java.awt.Dimension(900, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddNewUser.setText("Add New User");
        jPanel1.add(btnAddNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel1.setText("Tìm kiếm user");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 15, 110, 40));

        txtLookupUser.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel1.add(txtLookupUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 15, 270, 40));

        tableUsers.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Serial", "User Name", "Email", "Organization", "Address", "Actived", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableUsers.setRowHeight(25);
        tableUsers.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tableUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, -1));

        btnCreatePass.setText("Create Password");
        jPanel1.add(btnCreatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnCreatePass;
    private javax.swing.JButton btnHash;
    private javax.swing.JDialog dialogAddNewUser;
    private javax.swing.JDialog dialogCreatePassword;
    private javax.swing.JDialog dialogEditUser;
    private javax.swing.JDialog dialogPackSoftware;
    private javax.swing.JButton dlAddNewUser_Add;
    private javax.swing.JTextField dlAddNewUser_Address;
    private javax.swing.JTextField dlAddNewUser_Email;
    private javax.swing.JTextField dlAddNewUser_FullName;
    private javax.swing.JTextArea dlAddNewUser_Note;
    private javax.swing.JTextField dlAddNewUser_Organization;
    private javax.swing.JTextField dlAddress;
    private javax.swing.JButton dlBtnBuild;
    private javax.swing.JButton dlBtnSave;
    private javax.swing.JTextField dlEmail;
    private javax.swing.JTextField dlFullName;
    private javax.swing.JTextArea dlNote;
    private javax.swing.JTextField dlOrganization;
    private javax.swing.JTextField dlPackTxtPassword;
    private javax.swing.JTextField dlSerial;
    private javax.swing.JLabel dlSerialPackLogs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea logsPack;
    private javax.swing.JMenuItem menuItemEditUser;
    private javax.swing.JMenuItem menuItemPackSoftWare;
    private javax.swing.JMenuItem menuItemRemoveUser;
    private javax.swing.JPopupMenu popupTableUser;
    private javax.swing.JTable tableUsers;
    private javax.swing.JTextArea txtBcrypt;
    private javax.swing.JTextField txtLookupUser;
    private javax.swing.JTextField txtPlainTextPass;
    // End of variables declaration//GEN-END:variables
}
